server:
  port: 9090
  servlet:
    context-path: /demo-security


spring:
  security:
    user:
      name: test
      password: 123456
      roles: USER
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379
    password: 123456
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  config:
    key: test-key
    ttl: 600000
    remember: 604800000

custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/login"
        - "/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"

# /doc.html
knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: zh-CN
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: YFAN
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models