spring:
  application:
    name: demo-redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: zh-CN
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: YFAN
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models

