spring:
  application:
    name: demo-mysql-mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.yfan.demomysqlmybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  basic:
    enable: true


