server:
  port: 9090
  servlet:
    context-path: /demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
zk:
  url: 127.0.0.1:2181
  timeout: 1000
  retry: 3

knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: zh-CN
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: YFAN
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
