server:
  port: 9090
  servlet:
    context-path: /demo
  mvc:
      pathmatch:
          matching-strategy: ant_path_matcher
dubbo:
  application:
    name: demo-dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181

knife4j:
    enable: true
    documents:
        - group: Test Group
          name: My Documents
          locations: classpath:wiki/*
    setting:
        # default lang
        language: zh-CN
        # footer
        enableFooter: false
        enableFooterCustom: true
        footerCustomContent: YFAN
        # header
        enableHomeCustom: true
        homeCustomLocation: classpath:wiki/README.md
        # models
        enableSwaggerModels: true
        swaggerModelName: My Models

