server:
    port: 9090
    servlet:
        context-path: /demo

spring:
    dubbo:
        application:
            name: demo-dubbo-provider
            registry: zookeeper://192.168.40.131:2181

knife4j:
    enable: true
    setting:
        language: zh_cn
