server:
    port: 9090
    servlet:
        context-path: /demo

dubbo:
    application:
        name: demo-dubbo-provider
    protocol:
        name: dubbo
        port: -1
    registry:
        address: zookeeper://127.0.0.1:2181

knife4j:
    enable: true
    setting:
        language: zh_cn

