server:
  port: 8080

spring:
  application:
    name: demo-redisson
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password: 123456
  redisson:
    host: 127.0.0.1
    port: 6379
    password: 123456
#    # 哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 192.168.10.106:6209,192.168.10.106:6219,192.168.10.106:6229
#    # 集群模式
#    cluster: 192.168.10.106:6109,192.168.10.106:6119,192.168.10.106:6129


knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: zh-CN
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: YFAN
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models

