server:
  port: 9091
  servlet:
    context-path: /demo

spring:
  dubbo:
    application:
      name: demo-dubbo-consumer
      registry: zookeeper://192.168.40.131:2181



knife4j:
  enable: true
  setting:
    language: zh_cn

