server:
  port: 9091
  servlet:
    context-path: /demo

dubbo:
  application:
    name: demo-dubbo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181

knife4j:
  enable: true

